List<Map<String, dynamic>> itemData() => [
      {
        "name": "The Walking Dead",
        "desc": "Sheriff Deputy Rick Grimes wakes up from a coma to learn the world is in ruins and must lead a group of survivors to stay alive.",
        "duration": "44m",
        "year": "2010 - 2022",
        "age": "20+",
        "rate": "8.1",
        "photo0": "assets/image2.jpg",
        "photo1": "assets/image2.1.jpeg",
        "photo2": "assets/image2.2.jpeg",
        "photo3": "assets/image2.3.jpeg",
        "photo4": "assets/image2.4.jpeg",
        "photo5": "assets/image2.5.jpeg",
        "id": 1,
      },
      {
        "name": "Joker",
        "desc": "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
        "duration": "2j 2m",
        "year": "2019",
        "age": "17+",
        "rate": "8.4",
        "photo0": "assets/image1.jpg",
        "photo1": "assets/image1.1.jpg",
        "photo2": "assets/image1.2.jpeg",
        "photo3": "assets/image1.3.jpeg",
        "photo4": "assets/image1.4.jpeg",
        "photo5": "assets/image1.5.jpeg",
        "id": 2,
      },
      {
        "name": "Aladdin",
        "desc": "A kind-hearted street urchin and a power-hungry Grand Vizier vie for a magic lamp that has the power to make their deepest wishes come true.",
        "duration": "2j 8m",
        "year": "2019",
        "age": "13+",
        "rate": "6.9",
        "photo0": "assets/image3.jpg",
        "photo1": "assets/image3.1.jpg",
        "photo2": "assets/image3.2.jpg",
        "photo3": "assets/image3.3.jpeg",
        "photo4": "assets/image3.4.jpg",
        "photo5": "assets/image3.5.jpg",
        "id": 3,
      },
      {
        "name": "Avengers: Endgame",
        "desc": "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
        "duration": "3j 1m",
        "year": "2019",
        "age": "13+",
        "rate": "8.4",
        "photo0": "assets/image4.jpg",
        "photo1": "assets/image4.1.jpg",
        "photo2": "assets/image4.2.jpg",
        "photo3": "assets/image4.3.jpg",
        "photo4": "assets/image4.4.jpg",
        "photo5": "assets/image4.5.jpg",
        "id": 4,
      },
      {
        "name": "Alice in Borderland",
        "desc": "Obsessed gamer Arisu suddenly finds himself in a strange, emptied-out version of Tokyo in which he and his friends must compete in dangerous games in order to survive.",
        "duration": "50m",
        "year": "2020",
        "age": "18+",
        "rate": "7.7",
        "photo0": "assets/image5.jpg",
        "photo1": "assets/image5.1.jpeg",
        "photo2": "assets/image5.2.jpg",
        "photo3": "assets/image5.3.jpg",
        "photo4": "assets/image5.4.jpg",
        "photo5": "assets/image5.5.jpg",
        "id": 5,
      },
      {
        "name": "The Batman",
        "desc": "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
        "duration": "2j 56m",
        "year": "2022",
        "age": "13+",
        "rate": "7.8",
        "photo0": "assets/image6.jpg",
        "photo1": "assets/image6.1.jpg",
        "photo2": "assets/image6.2.jpg",
        "photo3": "assets/image6.3.jpg",
        "photo4": "assets/image6.4.jpg",
        "photo5": "assets/image6.5.jpg",
        "id": 6,
      },
    ];
